server:
  type: simple
  applicationContextPath: /v1/cognitive/enhancement
  adminContextPath: /admin
  connector:
    type: http
    port: 5010

logging:
  level: INFO
  loggers:
    com.bankia: DEBUG

kafka:
  brokers: kafka:29092

  producer:
    topic: "classification"
    failureTopic: "failed"
    acks: "1"
    client.id: "api"
    batch.size: 1

  consumer:
    parallelism: 1
    topic: "enhancement"
    group.id: "enhancement"
    enable.auto.commit: false
    # long timeout during development / testing for debugger
    session.timeout.ms: "300000"
    request.timeout.ms: "310000"
    auto.offset.reset: "earliest"

hbase:
  namespace: "BG_COGNITIVE"

  config:
    hbase.zookeeper.quorum: "hbase"
    hbase.zookeeper.property.clientPort: "2181"
    hbase.client.retries.number: 2
    hbase.rpc.timeout: 5000

captiva:
  username: "teradata"
  password: "$teradata.1"
  url: "http://vlibkd007:81/repos/ocr/"
  #url: "http://requestbin.fullcontact.com/1m3v6qr1/"
  urlCaptiva: "http://conit-pu.cm.es/bisa/rest/snendpoint/GenerarFicherosXMLDocumentoHerramientaCapturaSNG/1.0/"
  #urlCaptiva: "http://requestbin.fullcontact.com/1m3v6qr1/snendpoint/GenerarFicherosXMLDocumentoHerramientaCapturaSNG/1.0/"

  #kerberos:
  #  principal:
  #  keytab:
  #  refreshIntervalHours: